---
title: "Gov 50 Final Project"
author: "Luísa Shida"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how individuals understand and act upon data privacy and the information they share in social media, applications, and technology as a whole. I would particularly be interested in exploring how education on data privacy relates to how careful individuals are in their data sharing choices, and how they conceive of issues of data exploitation.

## Proposal

Dataset: Pew Research Center: American Trends Panel Wave 49 - Data Privacy & Communications Technology

**Does an individual's level of education and knowledge on how their data is being used and shared digitally influence their attitude towards data sharing?** In this study, I intend on analyzing whether individuals who are more familiar with the framework of data privacy - particular concepts, laws and regulations, potential dangers and opportunities, etc. - tend to be more or less granular in their relationship with data sharing, that is, whether they are more or less cautious when choosing to share their information with companies, the government, and other institutions. I expect that individuals who have more knowledge on issues of data privacy will be more protective of their data and more careful in how they engage with technology, while individuals with less familiarity with the notions of data privacy will tend to be less attentive and more permissive with their data-sharing choices. I believe this hypothesis might be true since individuals with more knowledge on data privacy will most likely be more aware of the potential dangers that surround sharing personal information with companies and services, therefore looking to prevent these dangers from happening to them. On the other hand, individuals who are not aware of the perils of data sharing might not be afraid of engaging with technology more freely, given that they might not fully comprehend the risks involved with sharing their data. In order to test this hypothesis, I will specifically focus on the variables of this dataset which explore how familiar the respondents of this survey are with important concepts to understanding the framework of data privacy; I am particularly interested in question 4, which asks how much the respondents have read about facial recognition technologies (to which possible responses are "a lot", "a little" or "nothing at all"), and questions 15-24, which ask the respondents to determine whether a set of data privacy-related statements are conceptually true or not. While these variables indicate how familiar the respondent is to data privacy concepts, other variables ask how they feel regarding the safety of their data, how concerned they are about their personal information getting shared, and how permissive they are to certain applications' data gathering settings - these questions represent my outcome variables of interest, since they make up a respondent's attitude towards data sharing. Should respondents who correctly answer questions 15-24, demonstrating their knowledge on data privacy, reveal that they are restrictive and critical in their information sharing through their answers to the latter set of questions, my hypothesis will be proven. Otherwise, if respondents who show command of data privacy topics indicate that they are permissive with the sharing of their data, my hypothesis will be disproven.

```{r}
library(tidyverse)
dataprivacy <- read_csv("dataprivacy.csv")
head(dataprivacy)
```


